# Generated by Django 3.0.3 on 2020-04-04 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ongs', '0003_auto_20200404_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='ong',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome'),
        ),
    ]
