# Generated by Django 3.0.3 on 2020-04-01 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ongs', '0001_initial'),
        ('incidents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='ong',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ongs.Ong'),
            preserve_default=False,
        ),
    ]
