# Generated by Django 3.0.3 on 2020-08-10 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ongs', '0004_ong_name'),
        ('incidents', '0003_incident_value_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='ong',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ongs.Ong'),
        ),
    ]
